INSERT INTO PUBLIC.CURRENCY (ID, NAME, CODE) VALUES (1, 'USD', 840);
INSERT INTO PUBLIC.CURRENCY (ID, NAME, CODE) VALUES (2, 'UAH', 980);

INSERT INTO PUBLIC.UNITMEASURE (ID, NAME) VALUES (1, 'item');
INSERT INTO PUBLIC.UNITMEASURE (ID, NAME) VALUES (2, 'kilogram');


INSERT INTO PUBLIC.PRODUCT (NAME, PRICE, CURRENCY_ID, UNITMEASURE_ID) VALUES ('apple', 1.20, 1, 2);
INSERT INTO PUBLIC.PRODUCT (NAME, PRICE, CURRENCY_ID, UNITMEASURE_ID) VALUES ('cherry', 2.99, 1, 2);
INSERT INTO PUBLIC.PRODUCT (NAME, PRICE, CURRENCY_ID, UNITMEASURE_ID) VALUES ('milk', 0.85, 1, 1);
INSERT INTO PUBLIC.PRODUCT (NAME, PRICE, CURRENCY_ID, UNITMEASURE_ID) VALUES ('coffee', 12.99, 1, 2);
